version: '1'

services:
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - fleetingflow
    # ports:
    #   - "6179:6379"

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./backend/document/:/docker-entrypoint-initdb.d/
    networks:
      - fleetingflow
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=qiniu"
      - "TZ=Asia/Shanghai"
    restart: always
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  aiapps:
    container_name: aiapps
    build:
      context: ./machine-learning
    networks:
      - fleetingflow
    depends_on:
      - mysql
    restart: always
    links:
      - mysql
    ports:
      - "7671:7671"
      - "7670:7670"

networks:
  # 默认将会创建为 docker-compose.yml所在 文件夹名_my_network 网络名称
  fleetingflow:
    driver: bridge