version: '1'

services:
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - fleetingflow
    # ports:
    #   - "6179:6379"

  mysql:
    container_name: mysql
    image: mysql:5.7
    

networks:
  # 默认将会创建为 docker-compose.yml所在 文件夹名_my_network 网络名称
  fleetingflow: