server:
  port: 4000

spring:
  application:
    name: gateway
  cloud:
    nacos:
      config:
        server-addr: 10.60.98.242:8848
        file-extension: yml
      discovery:
        server-addr: 10.60.98.242:8848

    gateway:
      routes:
        # 用户服务
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**, /foot/**, /login/**
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/video/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment/**
        - id: not-found
          uri: lb://user-service
          predicates:
            - Path=/**
          order: 10000
      globalcors:
        add-to-simple-url-handler-mapping: true # 放行options请求
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: # 允许的跨域ajax请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 本次跨域检查的有效期

  zipkin:
    base-url: http://10.60.98.242:9411/
    discovery-client-enabled: false   # 禁用服务发现客户端
    sender: rabbit
    compression:
      enabled: false      # 禁用跟踪数据的压缩

  sleuth:
    sampler:
      probability: 1    # 采样率

  config:
    import:
      - optional:nacos:gateway.yml
      - gateway-service.yaml
      - public-security.yaml

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
