ai:
  config:
    # tag推荐系统
    tag_recommend_system_url: "http://localhost:7672/run/predict"
    # 视频推荐系统
    video_recommend_system_url: "http://localhost:7676/run/predict"
    # 分类推荐系统
    category_recommend_system_url: "http://10.60.99.144:7675/run/predict"