server:
  port: 8002
  servlet:
    session:
      timeout: 5m # 设置session的有效期为五分钟
  address: 0.0.0.0

spring:
  application:
    name: comment-service
  cloud:
    nacos:
      config:
        server-addr: 10.60.98.242:8848
        file-extension: yml
      discovery:
        server-addr: 10.60.98.242:8848
  main:
    allow-circular-references: true
  config:
    import:
      - application-dal.yaml
      - default-feign.yaml
      - optional:nacos:comment-service.yml

database:
  name: qiniu

logging:
  level:
    root: info
    feign.Logger: debug